#!/usr/bin/env python3
"""Provision a fresh book's `factcheck/` — and prove it works.

## Why this is a script and not a paragraph

The technology is meant to be lifted onto another book. Until now, what
exactly travels existed only as a sentence in `README.md`: METHOD.md, the
tools, the empty directories. That sentence was true when written and
would have been wrong within a week, because nothing exercised it.

This project has learned that law repeatedly and expensively:

> A promise in the text is an invariant too. It must either hold or be
> removed from the text. An unkept promise is worse than an absent one:
> an absent one is visible, and an unkept one is relied upon.

Three times a document promised something the code did not do —
`factcheck.py vorota` promised two checks and made one, `measure_f.py`
counted before its own gate, `sweep.py` promised a candidate per batch and
silently skipped the line. Each was found by someone *trying to use* the
promise, never by reading it.

So "here is what travels" is written as a script. Running it is the test.
If somebody adds a tool the next book needs and does not make it travel,
provisioning fails on the day the omission is made, not on the morning the
next book starts.

## What it does

    factcheck/tools/newbook.py ../next-book

  1. creates `<target>/factcheck/` with the working directories
  2. copies METHOD.md and every tool
  3. writes a starter README.md, an empty REPORT.md, and `book.yaml`
  4. **runs the new tree's own self-checks** and fails if they fail
  5. checks that the copy REFUSES to run until `book.yaml` is filled in

Step 5 matters as much as step 4. A copy that runs unconfigured would run
against the wrong directories and report a confident zero, which is the
defect family this project catalogues above all others.

**The one thing to do next: edit `<target>/factcheck/book.yaml`.** The
title and the book's own directories live there and nowhere else.

Step 4 is the whole point. A copy that has not been shown to run is a
claim, and this file exists because claims drift.

## What it deliberately does not copy

Evidence, cards, reports, the cache, the archive, the run ledger — every
one of those is about *this* book. A new book that started with them would
begin by inheriting somebody else's findings, which is the self-reference
defect at the largest possible scale.
"""
from __future__ import annotations

import shutil
import subprocess
import sys
from pathlib import Path

import repo
from repo import ROOT  # noqa: E402  (root is found, not counted)

# What travels. Not a glob: this list is a STATEMENT about what the
# technology consists of, and `name_lists.py` checks that every name in it
# is the name of a file that exists.
TRAVELS = ["METHOD.md", "LESSONS.md"]

# What does NOT travel, and must be written fresh: everything specific to
# a book. Until `book.yaml` existed, these two facts lived in the tools —
# the chapter directories as a hardcoded `GRUPY` in eight of them, the
# title in `report.py` — so a new book inherited another book's structure
# and another book's name, silently, and would have found them by grep.
BOOK_YAML = """# What is specific to this book. The technology reads it; no
# tool repeats it. **Edit this before anything else.**

title: PUT THE BOOK'S NAME HERE

# The book's own directories, in reading order, relative to the repository
# root. One registry file is kept per file found here, under
# `factcheck/cards/`, with the same name.
#
# These must exist. A group that does not exist is silently empty, and an
# empty group reads as a book with no text in it — so `config.py` refuses
# to load rather than let that happen.
groups:
  - manual
"""

# The new book's empty directories. No data travels — none at all.
DIRS = ["cards", "evidence", "reports", "work/queues", "work/triage",
        "work/runs", "work/snapshots", "archive", "source-cache"]

README = """# `factcheck/`

> **canonical** — the decision lives here; there are to be no copies

Two documents, and everything they are about.

    METHOD.md   the technology — three layers, the laws of a work order,
                gates, sources, measurement. Not about any one book.

    REPORT.md   the fact-check of *this* book. Generated by
                `factcheck/tools/report.py`; empty until the registry has
                something in it.

## Everything else

    tools/         the fact-check tools
    source-cache/  source documents as downloaded. **Not in git.**
                   `MANIFEST.md` is: URL, name, size, sha256, date.
    cards/         one registry file per book file, mirroring the book
    evidence/      the evidence records
    reports/       the detail behind REPORT.md
    work/          queues, triage, runs, snapshots — state between waves
    archive/       spent work; nothing deleted, translated or renamed

## First steps

    factcheck/tools/factcheck.py sketch    build the registry from the book
    factcheck/tools/factcheck.py status    see where it stands
    factcheck/tools/report.py              write REPORT.md

Read `METHOD.md` Part I §0 first: what "fact-checking is finished" is
allowed to mean. Getting that wrong is more expensive than any tool here
can repair.
"""

GITIGNORE = """source-cache/*
!source-cache/MANIFEST.md
__pycache__/
"""


def provision(target: Path, dry_run: bool = False) -> int:
    fc = target / "factcheck"
    if fc.exists() and any(fc.iterdir()):
        print(f"   ✗ {fc} already exists and is not empty")
        return 1
    print(f"  provisioning {fc}")
    if not dry_run:
        (fc / "tools").mkdir(parents=True)
        for d in DIRS:
            (fc / d).mkdir(parents=True, exist_ok=True)
            (fc / d / ".gitkeep").touch()
        for name in TRAVELS:
            shutil.copy2(ROOT / "factcheck" / name, fc / name)
        for t in sorted((ROOT / "factcheck" / "tools").glob("*.py")):
            shutil.copy2(t, fc / "tools" / t.name)
        (fc / "README.md").write_text(README, encoding="utf-8")
        (fc / "REPORT.md").write_text(
            "# The fact-check of this book\n\n"
            "> **generated** — `factcheck/tools/report.py`. Nothing has been\n"
            "> measured yet: run `factcheck.py sketch` first.\n",
            encoding="utf-8")
        (fc / ".gitignore").write_text(GITIGNORE, encoding="utf-8")
        (fc / "book.yaml").write_text(BOOK_YAML, encoding="utf-8")
    n = len(list((fc / "tools").glob("*.py"))) if not dry_run else 0
    print(f"  copied {len(TRAVELS)} document(s), {n} tools, "
          f"{len(DIRS)} directories")
    return 0


def prove(target: Path) -> int:
    """Show that the copy runs. A copy nobody ran is a claim.

    Without this step the script merely moves files and reports success
    in exactly the words it would use having forgotten half of them."""
    tools = target / "factcheck" / "tools"
    ok = True
    for tool, arg in (("task_spec.py", "--version"),
                      ("paths.py", "--demo"),
                      ("config.py", "--demo"),
                      ("language.py", "--proba")):
        r = subprocess.run([sys.executable, str(tools / tool), arg],
                           capture_output=True, text=True, cwd=target)
        ok_one = r.returncode == 0
        print(f"   {'✓' if ok_one else '✗'} {tool} {arg}"
              + ("" if ok_one else f"\n{r.stdout[-400:]}{r.stderr[-400:]}"))
        ok &= ok_one
    # The spec must yield THE SAME order_version as here: otherwise the
    # new book briefs its helpers with different text under the same
    # number, and the two books' runs are silently incomparable.
    here = subprocess.run([sys.executable,
                          str(ROOT / "factcheck/tools/task_spec.py"),
                          "--version"], capture_output=True, text=True).stdout
    there = subprocess.run([sys.executable, str(tools / "task_spec.py"),
                          "--version"], capture_output=True, text=True,
                         cwd=target).stdout
    same = here.strip() == there.strip()
    print(f"   {'✓' if same else '✗'} order_version carried over: "
          f"{here.strip()} vs {there.strip()}")

    # І остання перевірка — найважливіша для нової книги: копія мусить
    # ВІДМОВИТИСЯ працювати, доки її не налаштували. Заготовка `book.yaml`
    # називає теку `manual`, якої в новому дереві може не бути; якщо
    # `config.py` таке проковтне, уся технологія піде по порожньому
    # переліку файлів і доповість упевнений нуль.
    #
    # Тобто ми перевіряємо не те, що копія працює, а те, що вона не
    # вдає роботу.
    r = subprocess.run([sys.executable, str(tools / "config.py")],
                       capture_output=True, text=True, cwd=target)
    nalashtovana = (target / "manual").is_dir()
    dobre = (r.returncode == 0) if nalashtovana else (r.returncode != 0)
    print(f"   {'✓' if dobre else '✗'} config refuses to run unconfigured"
          if not nalashtovana else
          f"   {'✓' if dobre else '✗'} config loads")
    return 0 if (ok and same and dobre) else 1


def main() -> int:
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    if not args:
        print(__doc__.split("## What it does")[1].split("##")[0].strip())
        return 2
    target = Path(args[0]).resolve()
    target.mkdir(parents=True, exist_ok=True)
    if provision(target, "--dry-run" in sys.argv):
        return 1
    if "--dry-run" in sys.argv:
        return 0
    print("  proving the copy runs:")
    return prove(target)


if __name__ == "__main__":
    sys.exit(main())
